package enums;

public enum GameStateEnum {

	START_GAME,
	ANIMATING,
	START_NEXT_TURN,
	SELECT_DICE_OR_CONTINUE,
	RESOLVE_DICE_ROLLS,
	CHOOSE_SKILL_TO_INCREASE,
	SELECT_DICE_TO_KEEP,
	MIZUAGE_TURN,

}
